### ISSUE TITLE
Example for builtin numpy solution?

### ISSUE THREAD

**Issue by kootenpv** [timothycrosley/preconvert#3]
In the quickstart you have the example:

    @preconvert.always(numpy.integer)
    def numpy_integer_to_python_int(numpy_int):
        return int(numpy_int)

But is there not already a builtin way that numpy (and maybe datetime) will work when using preconvert's `json`?

Maybe under the example you could point to this, if it exists.

**Comment by timothycrosley** [comment]
Thanks for pointing this out! I've added some initial additional documentation to try to make this more clear:

https://github.com/timothycrosley/preconvert/pull/4/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

Thanks!

~Timothy

**Comment by kootenpv** [comment]
Sweet! It is very clear!

I was wondering though whether you want to activate extensions **by being installed** rather than being **explicitly** (think Zen of Python) **enabled** (even if by a default setting).

Maybe I am misunderstanding it, but it sounds amazing anyway.
